### ISSUE TITLE
[FEATURE] - A popup window for GUI installation of apps

### ISSUE THREAD

**Issue by beans9926** [tcet-opensource/tcet-linux-welcome#17]
### Describe the improvement

A new button on the Welcome app landing page, which on clicking brings up a new window which would allow the user to install apps by selecting from a long list of chosen apps by the team and suggested by the community.

The window will have sections based on the type of apps, for example: productivity, programming, communication, utilities, etc.

### Why do we need this?

- This is for an much easier on-boarding of users on the TCET-Linux distribution.

### Do you have a proposed solution?

- Addition of a script which will install all the apps
- Updating the UI of the application

### Do you want to work on this feature?

- [ ] I am willing to implement this feature.

### Terms and Conditions

- [X] I agree to follow this project's Code of Conduct

**Comment by bhumikadubey** [comment]
Could you please assign it to me?

**Comment by Akash6222** [comment]
> Could you please assign it to me?

Done 👍

**Comment by Akash6222** [comment]
This issue has been completed
