### ISSUE TITLE
[FEATURE] port aboutus to c 

### ISSUE THREAD

**Issue by 0xAtharv** [tcet-opensource/tcet-linux-welcome#20]
### Describe the improvement

rewrite the about us  section in gtk c .

### Why do we need this?

cuz c is faster than python

C > python 

### Do you have a proposed solution?

write aboutus in c

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

### Terms and Conditions

- [X] I agree to follow this project's Code of Conduct

**Comment by Akash6222** [comment]
@0xAtharv is it completed ?

**Comment by 0xAtharv** [comment]
need to integrate in the about us section + check if the aboutus section looks proper . @Akash6222

**Comment by Akash6222** [comment]
Ya sure I'll look into it in coming days 🤞

**Comment by Akash6222** [comment]
@0xAtharv What's update on this ?
